name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: ./mvnw -B spring-boot:build-image --file pom.xml -Dspring-boot.build-image.imageName=ghcr.io/4sitive/account
  deploy:
    needs: build
    runs-on: [ self-hosted ]
    steps:
      - name: Deploy with Docker
        env:
          KEY: ${{secrets.KEY}}
        run: |
          docker ps -q --filter "name=account" | grep -q . && docker stop account && docker rm -fv account
          docker run -e AUTHORIZATIONSERVERSECURITY_KEY=$KEY -d -p 18080:8080 -p 18081:8081 --name account --restart always ghcr.io/4sitive/account
